[package]
name = "erc20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
known-tokens = []

[dependencies]
alloy-primitives = "0.6"
alloy-sol-types = { version = "0.6", features = ["json"] }
alloy = { git = "https://github.com/alloy-rs/alloy", features = [
    "network",
    "providers",
    "transports",
    "transport-http",
    "rpc",
    "rpc-types",
    "rpc-client",
    "contract",
] }
tokio = { version = "1", features = ["full"] }
bigdecimal = "0.4"
thiserror = "1.0"
anyhow = "1.0"
once_cell = "1.18"
parking_lot = "0.12"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
reqwest = "0.11"
dotenv = "0.15"

[patch.crates-io]
alloy-sol-macro = { git = "https://github.com/alloy-rs/core", rev = "1bac7678797fcd1bee2f2580825724b4165b12c1" }
alloy-primitives = { git = "https://github.com/alloy-rs/core", rev = "1bac7678797fcd1bee2f2580825724b4165b12c1" }
alloy-sol-types = { git = "https://github.com/alloy-rs/core", rev = "1bac7678797fcd1bee2f2580825724b4165b12c1" }
alloy-json-abi = { git = "https://github.com/alloy-rs/core", rev = "1bac7678797fcd1bee2f2580825724b4165b12c1" }
alloy-dyn-abi = { git = "https://github.com/alloy-rs/core", rev = "1bac7678797fcd1bee2f2580825724b4165b12c1" }
syn-solidity = { git = "https://github.com/alloy-rs/core", rev = "1bac7678797fcd1bee2f2580825724b4165b12c1" }
alloy-core = { git = "https://github.com/alloy-rs/core", rev = "1bac7678797fcd1bee2f2580825724b4165b12c1" }
