[package]
name = "erc20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = ["dep:serde"]

[dependencies]
alloy-primitives = "0.5.1"
alloy-sol-types = { version = "0.5.1", features = ["json"] }
alloy-providers = { git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy" }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"], optional = true }

bigdecimal = "0.4"
thiserror = "1.0"
anyhow = "1.0"
async-recursion = "1.0"
once_cell = "1.18.0"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
reqwest = "0.11"
dotenv = "0.15"


[patch.crates-io]
alloy-primitives = { git = 'https://github.com/alloy-rs/core' }
