[package]
name = "erc20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
known-tokens = []

[dependencies]
alloy-primitives = "0.6"
alloy-sol-types = { version = "0.6", features = ["json"] }
alloy-providers = { git = "https://github.com/alloy-rs/alloy", rev = "d19dfe8" }
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy", rev = "d19dfe8" }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "d19dfe8" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy", rev = "d19dfe8" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "d19dfe8" }
tokio = { version = "1", features = ["full"] }
bigdecimal = "0.4"
thiserror = "1.0"
anyhow = "1.0"
once_cell = "1.18"
parking_lot = "0.12"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
reqwest = "0.11"
dotenv = "0.15"
