[package]
name = "erc20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = ["dep:serde"]

[dependencies]
ethers = { version = "2.0" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"], optional = true }
dashu-float = "0.4"
thiserror = "1.0"
anyhow = "1.0"
async-recursion = "1.0"
once_cell = "1.18.0"
