[package]
name = "erc20"
version = "0.1.0"
edition = "2021"
authors = ["leruaa"]
keywords = ["alloy", "ethereum", "erc20"]
categories = ["cryptography::cryptocurrencies", "data-structures"]
license = "MIT"
readme = "./README.md"
documentation = "https://docs.rs/erc20-rs"
repository = "https://github.com/leruaa/erc20-rs"
homepage = "https://github.com/leruaa/erc20-rs"
description = """
Interact with ERC-20 contracts via Alloy.
"""

[features]
known-tokens = []

[dependencies]
alloy = { version = "0.1", features = [
    "network",
    "providers",
    "transports",
    "transport-http",
    "rpc",
    "rpc-types",
    "rpc-client",
    "contract",
    "sol-types",
] }
futures = "0.3"
bigdecimal = "0.4"
thiserror = "1.0"
once_cell = "1.18"
async-once-cell = "0.5"
async-trait = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
reqwest = "0.12"
dotenv = "0.15"
